import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Context from "./pageContext";
import { Roboto } from 'next/font/google';

const roboto = Roboto({
  weight: ['100', '400', '700', '900'],
  subsets: ['latin'],
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: "Pratheek",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={roboto.variable + " antialiased h-dvh"}
      >
        <Context>
            {children}
        </Context>
      </body>
    </html>
  );
}
